<script type="text/javascript">
    var url_list_products = '{{route('list_product',['search'=>'key_word'])}}';
    var base_url = '{{route('user')}}';
    var add_cart_ajax = '{{route('add_cart_ajax')}}';
    var list_cart = '{{route('list_cart')}}';
    var get_menu_mobile = '{{route('get_menu_mobile')}}';
    var get_menu_child = '{{route('get_menu_child')}}';
    var get_hot_sale_mobile = '{{route('get_hot_sale_mobile')}}';
    var get_new_mobile = '{{route('get_new_mobile')}}';
    var get_promotion_mobile = '{{route('get_promotion_mobile')}}';
    var get_category_promotion_mobile = '{{route('get_category_promotion_mobile')}}';
    var get_product_mobile = '{{route('get_product_mobile')}}';
    var get_product_category_child_mobile = '{{route('get_product_category_child_mobile')}}';
    var get_product_watched = '{{route('get_product_watched')}}';
    var get_product_similar = '{{route('get_product_similar')}}';
    var product_cat = '{{route('product_cat',['slug' => 'slug_code'])}}';
    var commentProduct = '{{route('commentProduct')}}';
    var detailproduct = '{{route('detailproduct', ['slug' => 'slug_code'])}}';
    var get_review_more = '{{route('get_review_more')}}';
    var update_shopping_cart = '{{route('update_shopping_cart')}}';
    var remove_cart_data = '{{route('remove_cart_data')}}';
    var order_processing = '{{route('order_processing')}}';
    var checkout = '{{route('checkout')}}';
    var product_views = '{{route('product_views')}}';
    var successorder = '{{route('successorder')}}';
    var complete_payment = '{{route('complete_payment')}}';
    var get_district = '{{route('get_district')}}';
    var autotypeahead = '{{route('autotypeahead')}}';
    var url_new_product = '{{route('list_product',['promotion'=>'san-pham-moi'])}}';
    var url_hot_product = '{{route('list_product',['promotion'=>'san-pham-hot'])}}';
    var url_promotion_product = '{{route('list_product',['promotion'=>'san-pham-khuyen-mai'])}}';
    var img_product_mobile = '{{asset('upload/images/products/thumb/img_name')}}';
    var common_img_mobile = '{{asset('upload/images/common_img/img_name')}}';
    var url_img_thumb_product= '{{asset('upload/images/products/thumb/')}}';
    var url_img_large_product= '{{asset('upload/images/products/large/')}}';
    var img_brands = '{{asset('upload/images/products/thumb/img_name')}}';
    var img_category = '{{asset('upload/images/products/thumb/img_name')}}';
    var img_detailproperties = '{{asset('upload/images/detailproperties/thumb/img_name')}}';
</script>
